version: '3.7'
  
services:
    jayeon-nginx:
        container_name : jayeon-nginx
        build:
            context: /compose/jayeon
            dockerfile: DockerfileNginx
        ports:
            - 80:80
        user: root
    jayeon-front:
        build: .
        container_name: jayeon-front
        user: root
        expose: 
            - 3000
        volumes:
            - /volumes:/volumes
