version: '3.7'
  
services:
    jenkins:
        container_name: jenkins
        image: ililil9482/jenkins_arm
        volumes:
            - ./data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        privileged: true
        user: root
        restart: always
